# Generated by Django 3.0.4 on 2020-03-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
